routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\ProblemaController;
use App\Http\Controllers\CalificacionController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\ReenviadoController;
use App\Http\Controllers\KidController;
use App\Http\Controllers\PuntuacionController;
use App\Http\Livewire\ListaRanking;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>['auth']],function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('calificaciones/{id}',[CalificacionController::class,'vercalificacion'])->name('calificaciones.ver');
    Route::get('calificaciones/{id}/{estado}',[ListaRanking::class,'estado'])->name('calificaciones.estado');
    Route::resource('usuarios',UsuarioController::class);
    Route::resource('roles',RolController::class);
    Route::resource('problemas',ProblemaController::class);
    Route::resource('calificaciones',CalificacionController::class);
    Route::resource('equipos',EquipoController::class);
    Route::resource('estudiantes',EstudianteController::class);
    Route::resource('puntuacions',PuntuacionController::class);

});
Route::resource('reenviados',ReenviadoController::class);

Route::get('kid/login', [KidController::class,'login'])->name('kid.login');
Route::post('kid/login', [KidController::class,'autenticacion'])->name('kid.auth');
Route::post('kid/logout', [KidController::class,'logout'])->name('kid.logout');
Route::get('concursos',[ProblemaController::class,'concurso'])->name('concursos.index')->middleware('authteam');
Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show')->middleware('authteam');


Route::get('ranking',[ProblemaController::class,'getranking'])->name('ranking.index');



//Route::get('calificaciones/{id}/{estado}',[CalificacionController::class,'estado'])->name('calificaciones.estado');





Route::get('no_autorizado',function (){
    return "no autorizado";
});


//Route::post('loginconcurso', [ProblemaController::class,'postlogin'])->name('concurso.login');

// Route::get('loginconcurso', [ProblemaController::class,'login'])->name('concurso.ver');
//Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show');



Route::get('rktest',[ProblemaController::class,'onlytest'])->name('ranking.test');

app/Models/Estudiante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Estudiante extends Model
{
    use HasFactory;
    public function equipo(){
        return $this->belongsTo(Equipo::class);
    }
}

app/Http/Controllers/EstudianteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Equipo;
use App\Models\Estudiante;
use Illuminate\Http\Request;

class EstudianteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estudiante = Estudiante::all();
        return view('estudiante.index', compact('estudiante'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $equipo = Equipo::all();
        return view('estudiante.create', compact('equipo'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required',
            'apellidop' => 'required',
            'apellidom' => 'required',
            'dni' => 'required',
            'equipo' => 'required',
        ]);

        $estudiante = new Estudiante();

        $estudiante->nombre = $request->nombre;
        $estudiante->apellido_p = $request->apellidop;
        $estudiante->apellido_m = $request->apellidom;
        $estudiante->dni = $request->dni;
        $estudiante->equipo_id = $request->equipo;

        $estudiante->save();

        return redirect()->route('estudiantes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function show(Estudiante $estudiante)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function edit(Estudiante $estudiante)
    {
        $equipo = Equipo::all();
        return view('estudiante.edit', compact('estudiante','equipo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Estudiante $estudiante)
    {
        $request->validate([
            'nombre' => 'required',
            'apellidop' => 'required',
            'apellidom' => 'required',
            'dni' => 'required',
            'equipo' => 'required',
        ]);

        $estudiante->nombre = $request->nombre;
        $estudiante->apellido_p = $request->apellidop;
        $estudiante->apellido_m = $request->apellidom;
        $estudiante->dni = $request->dni;
        $estudiante->equipo_id = $request->equipo;

        $estudiante->save();

        return redirect()->route('estudiantes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Estudiante  $estudiante
     * @return \Illuminate\Http\Response
     */
    public function destroy(Estudiante $estudiante)
    {
        $estudiante->delete();

        return redirect()->route('estudiantes.index');
    }
}

resources/views/estudiante/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>CREAR ESTUDIANTE</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('estudiantes.store')}}" method="POST">
            @method('POST')
            @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Apellido Paterno</label>
                        <input type="text" class="form-control" id="apellidop" name="apellidop">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Apellido Materno</label>
                        <input type="text" class="form-control" id="apellidom" name="apellidom">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Dni</label>
                        <input type="text" class="form-control" id="dni" name="dni">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Equipo</label>
                        <select id="inputState" class="form-control" name="equipo">
                            @foreach ($equipo as $item)
                            <option value="{{$item->id}}">{{$item->nombre}}</option>
                            @endforeach
                        </select>
                    </div>

                </div>
                <a href="{{route('estudiantes.index')}}" class="btn btn-primary ">Regresar</a>
                <button type="submit" class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/estudiante/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>EDITAR ESTUDIANTE</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('estudiantes.update', $estudiante)}}" method="POST">
            @method('put')
            @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre"  value="{{$estudiante->nombre}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Apellido Paterno</label>
                        <input type="text" class="form-control" id="apellidop" name="apellidop" value="{{$estudiante->apellido_p}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Apellido Materno</label>
                        <input type="text" class="form-control" id="apellidom" name="apellidom" value="{{$estudiante->apellido_m}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Dni</label>
                        <input type="text" class="form-control" id="dni" name="dni" value="{{$estudiante->dni}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Equipo</label>
                        <select id="inputState" class="form-control" name="equipo">
                        @foreach ($equipo as $item)
                        <option value="{{$item->id}}" {{ old('equipo', $estudiante->equipo_id) == $item->id ? 'selected' : '' }}>{{$item->nombre}}</option>
                        @endforeach
                        </select>
                    </div>

                </div>
                <a href="{{route('estudiantes.index')}}" class="btn btn-primary ">Regresar</a>
                <button type="submit" class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/estudiante/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <a class="btn btn-success mb-2" href="{{route('estudiantes.create')}}" role="button">Crear nuevo estudiante</a>
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="testudiantes" >
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombres</th>
                        <th scope="col">Apellido Paterno</th>
                        <th scope="col">Apellido Materno</th>
                        <th scope="col">Dni</th>
                        <th scope="col">Equipo</th>
                        <th scope="col">acciones</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($estudiante as $estudiante)
                        <tr>
                            <th>{{$estudiante->id}}</th>
                            <td>{{$estudiante->nombre}}</td>
                            <td>{{$estudiante->apellido_p}}</td>
                            <td>{{$estudiante->apellido_m}}</td>
                            <td>{{$estudiante->dni}}</td>
                            <td>{{$estudiante->equipo_id}}</td>
                            <td width="100px">
                                <a class="btn btn-warning" href="{{route('estudiantes.edit',$estudiante->id)}}" role="button"><i class="fas fa-edit"></i></a>
                                <form action="{{route('estudiantes.destroy', $estudiante)}}" method="post"  style="display: inline">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                </form>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
    <script>
        $(document).ready(function () {
            $('#testudiantes').DataTable({
                responsive: true,
                autoWidth: false,
                "language": {
                    "url": "{{asset("idioma/es_dtable.json")}}"
                }
            });
        });
    </script>
@stop