routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\ProblemaController;
use App\Http\Controllers\CalificacionController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\ReenviadoController;
use App\Http\Controllers\KidController;
use App\Http\Controllers\PuntuacionController;
use App\Http\Livewire\ListaRanking;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>['auth']],function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('calificaciones/{id}',[CalificacionController::class,'vercalificacion'])->name('calificaciones.ver');
    Route::get('calificaciones/{id}/{estado}',[ListaRanking::class,'estado'])->name('calificaciones.estado');
    Route::resource('usuarios',UsuarioController::class);
    Route::resource('roles',RolController::class);
    Route::resource('problemas',ProblemaController::class);
    Route::resource('calificaciones',CalificacionController::class);
    Route::resource('equipos',EquipoController::class);
    Route::resource('estudiantes',EstudianteController::class);
    Route::resource('puntuacions',PuntuacionController::class);

});
Route::resource('reenviados',ReenviadoController::class);

Route::get('kid/login', [KidController::class,'login'])->name('kid.login');
Route::post('kid/login', [KidController::class,'autenticacion'])->name('kid.auth');
Route::post('kid/logout', [KidController::class,'logout'])->name('kid.logout');
Route::get('concursos',[ProblemaController::class,'concurso'])->name('concursos.index')->middleware('authteam');
Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show')->middleware('authteam');


Route::get('ranking',[ProblemaController::class,'getranking'])->name('ranking.index');



//Route::get('calificaciones/{id}/{estado}',[CalificacionController::class,'estado'])->name('calificaciones.estado');





Route::get('no_autorizado',function (){
    return "no autorizado";
});


//Route::post('loginconcurso', [ProblemaController::class,'postlogin'])->name('concurso.login');

// Route::get('loginconcurso', [ProblemaController::class,'login'])->name('concurso.ver');
//Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show');



Route::get('rktest',[ProblemaController::class,'onlytest'])->name('ranking.test');

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Testing\Fluent\Concerns\Has;
use Spatie\Permission\Models\Role;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $usuarios=User::all();
        return view('usuario.index',compact('usuarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $roles= Role::all();
        return view('usuario.crear',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd($request->all());
        $this->validate($request,[
            'name' =>'required',
            'email' =>'required|email|unique:users,email',
            'password' => 'required|same:conpassword',
            'rol' => 'required'
        ]);

        $input= $request->all();
        $input['password'] = Hash::make($input['password']);

        $user=User::create($input);
        $user->assignRole($request->input('rol'));


        return redirect()->route('usuarios.index')->with('info','se creo correctamente');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $usuario=User::find($id);
        $roles=Role::all();
        return view('usuario.editar',compact('roles','usuario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $usuario=User::find($id);

        if($request->input('password')){
            $this->validate($request,[
                'password' => 'same:conpassword',
            ]);
            $usuario->password=Hash::make($request->input('password'));
        }


        $usuario->name=$request->input('name');
        $usuario->email=$request->input('email');
        $usuario->save();
        DB::table('model_has_roles')->Where('model_id',$id)->delete();
        $usuario->assignRole($request->input('rol'));
        return redirect()->route('usuarios.index')->with('info','editado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        User::find($id)->delete();

        return redirect()->route('usuarios.index');
    }
}

resources/views/usuario/crear.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>CREAR USUARIO</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('usuarios.store')}}" method="POST">
                @method('POST')
                @csrf

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="name">Nombre</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="email">Correo</label>
                        <input type="email" class="form-control" id="email" name="email">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="password">Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="conpassword">Confirma Contraseña</label>
                        <input type="password" class="form-control" id="conpassword" name="conpassword">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="rol">Roles</label>
                        <select id="rol" class="form-control" name="rol">
                            @foreach($roles as $rol)
                                <option value="{{$rol->name}}">{{$rol->name}}</option>
                            @endforeach

                        </select>
                    </div>
                </div>


                <a href="{{route('usuarios.index')}}" class="btn btn-primary ">Regresar</a>
                <button class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/usuario/editar.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>EDITAR USUARIO</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('usuarios.update',$usuario)}}" method="POST">
                @method('PUT')
                @csrf

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="name">Nombre</label>
                        <input type="text" class="form-control" value="{{$usuario->name}}" id="name" name="name">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="email">Correo</label>
                        <input type="email" class="form-control" value="{{$usuario->email}}" id="email" name="email">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="password">Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="conpassword">Confirma Contraseña</label>
                        <input type="password" class="form-control" id="conpassword" name="conpassword">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="rol">Roles</label>
                        <select id="rol" class="form-control" name="rol">
                            @foreach($roles as $rol)
                                <option value="{{$rol->id}}"  {{ $usuario->roles->first()->id == $rol->id ? 'selected' : '' }}>
                                    {{$rol->name}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>


                <a href="{{route('usuarios.index')}}" class="btn btn-primary ">Regresar</a>
                <button class="btn btn-success float-right">Confirmar</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/usuario/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <a class="btn btn-success float-right" href="{{route('usuarios.create')}}" role="button">Crear nuevo Usuario</a>

    <h1>Usuarios</h1>
@stop

@section('content')
    @if(session('info'))
        <div class="alert alert-success">
            <strong>{{session('info')}}</strong>
        </div>

    @endif


    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="tproblemas" >
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">name</th>
                        <th scope="col">email</th>
                        <th scope="col">roles</th>
                        <th scope="col">acciones</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($usuarios as $usuario)
                        <tr>
                            <th scope="row">{{$usuario->id}}</th>
                            <td>{{$usuario->name}}</td>
                            <td>{{$usuario->email}}</td>
                            <td>
                                @foreach($usuario->roles as $urol)
                                    <h5><span class="badge bg-cyan">{{$urol->name}}</span></h5></td>
                                @endforeach
                            <td width="100px">
                                <a class="btn btn-warning" href="{{route('usuarios.edit',$usuario->id)}}" role="button"><i class="fas fa-edit"></i></a>

                                <form action="{{route('usuarios.destroy', $usuario)}}" method="post"  style="display: inline">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                </form>

                        </tr>

                    @endforeach


                    </tbody>
                </table>
            </div>

        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script>
        $(document).ready(function() {
            // show the alert
            $(".alert").first().hide().slideDown(500).delay(4000).slideUp(500, function () {
                $(this).remove();
            });
        });
    </script>
    <script> console.log('Hi!'); </script>
    <script>
        $(document).ready(function () {
            $('#tproblemas').DataTable({
                responsive: true,
                autoWidth: false,
                "language": {
                    "url": "{{asset("idioma/es_dtable.json")}}"
                }
            });
        });
    </script>
@stop