routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\ProblemaController;
use App\Http\Controllers\CalificacionController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\ReenviadoController;
use App\Http\Controllers\KidController;
use App\Http\Controllers\PuntuacionController;
use App\Http\Livewire\ListaRanking;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>['auth']],function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('calificaciones/{id}',[CalificacionController::class,'vercalificacion'])->name('calificaciones.ver');
    Route::get('calificaciones/{id}/{estado}',[ListaRanking::class,'estado'])->name('calificaciones.estado');
    Route::resource('usuarios',UsuarioController::class);
    Route::resource('roles',RolController::class);
    Route::resource('problemas',ProblemaController::class);
    Route::resource('calificaciones',CalificacionController::class);
    Route::resource('equipos',EquipoController::class);
    Route::resource('estudiantes',EstudianteController::class);
    Route::resource('puntuacions',PuntuacionController::class);

});
Route::resource('reenviados',ReenviadoController::class);

Route::get('kid/login', [KidController::class,'login'])->name('kid.login');
Route::post('kid/login', [KidController::class,'autenticacion'])->name('kid.auth');
Route::post('kid/logout', [KidController::class,'logout'])->name('kid.logout');
Route::get('concursos',[ProblemaController::class,'concurso'])->name('concursos.index')->middleware('authteam');
Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show')->middleware('authteam');


Route::get('ranking',[ProblemaController::class,'getranking'])->name('ranking.index');



//Route::get('calificaciones/{id}/{estado}',[CalificacionController::class,'estado'])->name('calificaciones.estado');





Route::get('no_autorizado',function (){
    return "no autorizado";
});


//Route::post('loginconcurso', [ProblemaController::class,'postlogin'])->name('concurso.login');

// Route::get('loginconcurso', [ProblemaController::class,'login'])->name('concurso.ver');
//Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show');



Route::get('rktest',[ProblemaController::class,'onlytest'])->name('ranking.test');

app/Models/Problema.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Problema extends Model
{
    use HasFactory;
    public function puntaciones(){
        return $this->hasMany(Puntuacion::class);
    }
}

app/Http/Controllers/ProblemaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Problema;
use App\Models\Puntuacion;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Equipo;
class ProblemaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $problemas=Problema::all();
        return view('problema.index',compact('problemas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('problema.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $problema = new Problema();
        $problema->titulo = $request->titulo;
        $problema->valor = $request->valor;
        $problema->descripcion = $request->descripcion;
        $problema->entradas = $request->entradas;
        $problema->salidas = $request->salidas;
        $problema->restricciones = $request->restricciones;
        $problema->problema = $request->problema;
        $problema->solucion = $request->solucion;

        $problema->save();
        return redirect()->route('problemas.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Problema  $problema
     * @return \Illuminate\Http\Response
     */
    public function show(Problema $problema)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Problema  $problema
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $problema=Problema::find($id);

        return view('problema.editar',compact('problema'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Problema  $problema
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $problema=Problema::find($id);

        $problema->titulo=$request->input('titulo');
        $problema->valor=$request->input('valor');
        $problema->descripcion=$request->input('descripcion');
        $problema->entradas=$request->input('entradas');
        $problema->salidas=$request->input('salidas');
        $problema->restricciones=$request->input('restricciones');
        $problema->problema=$request->input('problema');
        $problema->solucion=$request->input('solucion');
        $problema->save();
        return redirect()->route('problemas.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Problema  $problema
     * @return \Illuminate\Http\Response
     */
    public function destroy(Problema $problema)
    {
        //
        $problema->delete();
        return redirect()->route('problemas.index');
    }

    public function concurso()
    {
        //
        /*session(['alpha'=>'developer']);*/
        //dd(session()->get('alpha'));
        $team=auth()->guard('kids')->user();

        $estudiantes=DB::table('estudiantes')->where('equipo_id',$team->id)->get();
        $problemas=Problema::all();
        //dd($problemas);
        return view('concurso.index',compact('problemas','estudiantes'));
    }

    public function verproblema($id)
    {
        //
        $problemas=Problema::all();
        $problema_=Problema::find($id);

        $team=auth()->guard('kids')->user();
        $envios=DB::table('puntuacions')->where('equipo_id',$team->id)->where('problema_id',$id)->get();

        $estudiantes=DB::table('estudiantes')->where('equipo_id',$team->id)->get();
        $aceptado = Puntuacion::where('estado', 'Aceptado')->where('equipo_id',$team->id)->where('problema_id',$id)->first();
        $esperando = Puntuacion::where('estado', 'Enviado')->where('equipo_id',$team->id)->where('problema_id',$id)->first();
        return view('concurso.index',compact('problemas','problema_','estudiantes','envios','aceptado','esperando'));
    }

    public function getranking(){
        // --
        $puntuacion=Puntuacion::all();
        return view('concurso.ranking');
    }

    public function onlytest(){
        // --
        //$puntuacion=Puntuacion::all()->sortByDesc('aceptados');
        $equipos1 = Equipo::all()->sortByDesc('puntuacion')->reverse()->values()->groupBy('aceptados');
        $equipos=$equipos1->reverse()->values();
        //dd($equipos->reverse()->values()[0][0]->nombre);
        //$equipos = $equipos1->sortByDesc('puntuacion')->reverse()->values();

        //dd($equipos);
        return view('concurso.test',compact('equipos'));
    }
}

resources/views/problema/crear.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>CREAR PROBLEMA</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('problemas.store')}}" method="POST">
            @method('POST')
            @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="titulo">Titulo</label>
                        <input type="text" class="form-control" id="titulo" name="titulo">
                    </div>
                    <div class="form-group  col-md-6">
                        <label for="valor">Valor</label>
                        <input type="number" class="form-control" id="valor" name="valor">
                    </div>
                </div>
                <div class="form-group">
                    <label for="titulo">Descripcion</label>
                    <textarea class="form-control" id="descripcion" rows="3" name="descripcion"></textarea>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="entradas">Entradas</label>
                        <input type="text" class="form-control" id="entradas" name="entradas">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="salidas">Salidas</label>
                        <input type="text" class="form-control" id="salidas" name="salidas">
                    </div>
                </div>
                <div class="form-group">
                    <label for="restricciones">Restricciones</label>
                    <textarea class="form-control" id="restricciones" rows="3" name="restricciones"></textarea>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="problema">Problema</label>
                        <input type="text" class="form-control" id="problema" name="problema">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="solucion">Solucion</label>
                        <input type="text" class="form-control" id="solucion" name="solucion">
                    </div>
                </div>
                <a href="{{route('problemas.index')}}" class="btn btn-primary ">Regresar</a>
                <button type="submit" class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/problema/editar.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>EDITAR PROBLEMA</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('problemas.update',$problema)}}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="titulo">Titulo</label>
                        <input type="text" class="form-control" id="titulo" value="{{$problema->titulo}}" name="titulo">
                    </div>
                    <div class="form-group  col-md-6">
                        <label for="valor">Valor</label>
                        <input type="number" class="form-control" id="valor" value="{{$problema->valor}}" name="valor">
                    </div>
                </div>


                <div class="form-group">
                    <label for="titulo">Descripcion</label>
                    <textarea class="form-control" id="descripcion" value="" rows="3" name="descripcion">{{$problema->descripcion}}</textarea>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="entradas">Entradas</label>
                        <input type="text" class="form-control" value="{{$problema->entradas}}" id="entradas" name="entradas">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="salidas">Salidas</label>
                        <input type="text" class="form-control" value="{{$problema->salidas}}" id="salidas" name="salidas">
                    </div>
                </div>
                <div class="form-group">
                    <label for="restricciones">Restricciones</label>
                    <textarea class="form-control" id="restricciones"  value="" rows="3" name="restricciones">{{$problema->restricciones}}</textarea>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="problema">Problema</label>
                        <input type="text" class="form-control" value="{{$problema->problema}}" id="problema" name="problema">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="solucion">Solucion</label>
                        <input type="text" class="form-control" value="{{$problema->solucion}}" id="solucion" name="solucion">
                    </div>
                </div>
                <a href="{{route('problemas.index')}}" class="btn btn-primary ">Regresar</a>
                <button type="submit" class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/problema/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <a class="btn btn-success mb-2" href="{{route('problemas.create')}}" role="button">Crear nuevo Problema</a>
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="tproblemas" >
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">titulo</th>
                        <th scope="col">valor</th>
                        <th scope="col">entradas</th>
                        <th scope="col">salidas</th>
                        <th scope="col">problema</th>
                        <th scope="col">solucion</th>
                        <th scope="col">restricciones</th>
                        <th scope="col">acciones</th>
                        <th scope="col">descripcion</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($problemas as $problema)
                        <tr>
                            <th scope="row">{{$problema->id}}</th>
                            <td>{{$problema->titulo}}</td>
                            <td>{{$problema->valor}}</td>
                            <td>{{$problema->entradas}}</td>
                            <td>{{$problema->salidas}}</td>
                            <td>{{$problema->problema}}</td>
                            <td>{{$problema->solucion}}</td>
                            <td style="min-width: 200px;">{{$problema->restricciones}}</td>
                            <td width="100px">
                                <a class="btn btn-warning" href="{{route('problemas.edit',$problema->id)}}" role="button"><i class="fas fa-edit"></i></a>

                                <form action="{{route('problemas.destroy', $problema)}}" method="post"  style="display: inline">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                </form>
                            <td>{{$problema->descripcion}}</td>

                        </tr>

                    @endforeach


                    </tbody>
                </table>
            </div>

        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
    <script>
        $(document).ready(function () {
            $('#tproblemas').DataTable({
                responsive: true,
                autoWidth: false,
                "language": {
                    "url": "{{asset("idioma/es_dtable.json")}}"
                }
            });
        });
    </script>
@stop