routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\RolController;
use App\Http\Controllers\ProblemaController;
use App\Http\Controllers\CalificacionController;
use App\Http\Controllers\EquipoController;
use App\Http\Controllers\EstudianteController;
use App\Http\Controllers\ReenviadoController;
use App\Http\Controllers\KidController;
use App\Http\Controllers\PuntuacionController;
use App\Http\Livewire\ListaRanking;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware'=>['auth']],function(){
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('calificaciones/{id}',[CalificacionController::class,'vercalificacion'])->name('calificaciones.ver');
    Route::get('calificaciones/{id}/{estado}',[ListaRanking::class,'estado'])->name('calificaciones.estado');
    Route::resource('usuarios',UsuarioController::class);
    Route::resource('roles',RolController::class);
    Route::resource('problemas',ProblemaController::class);
    Route::resource('calificaciones',CalificacionController::class);
    Route::resource('equipos',EquipoController::class);
    Route::resource('estudiantes',EstudianteController::class);
    Route::resource('puntuacions',PuntuacionController::class);

});
Route::resource('reenviados',ReenviadoController::class);

Route::get('kid/login', [KidController::class,'login'])->name('kid.login');
Route::post('kid/login', [KidController::class,'autenticacion'])->name('kid.auth');
Route::post('kid/logout', [KidController::class,'logout'])->name('kid.logout');
Route::get('concursos',[ProblemaController::class,'concurso'])->name('concursos.index')->middleware('authteam');
Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show')->middleware('authteam');


Route::get('ranking',[ProblemaController::class,'getranking'])->name('ranking.index');



//Route::get('calificaciones/{id}/{estado}',[CalificacionController::class,'estado'])->name('calificaciones.estado');





Route::get('no_autorizado',function (){
    return "no autorizado";
});


//Route::post('loginconcurso', [ProblemaController::class,'postlogin'])->name('concurso.login');

// Route::get('loginconcurso', [ProblemaController::class,'login'])->name('concurso.ver');
//Route::get('concursos/{concurso}',[ProblemaController::class,'verproblema'])->name('concursos.show');



Route::get('rktest',[ProblemaController::class,'onlytest'])->name('ranking.test');

app/Models/Equipo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Equipo extends Authenticatable
{
    use HasFactory;
    protected $guard = 'kids';
    public function estudiantes(){
        return $this->hasMany(Estudiante::class);
    }
    public function puntuaciones(){
        return $this->hasMany(Puntuacion::class);
    }
}

app/Http/Controllers/EquipoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Equipo;
use Illuminate\Http\Request;
use PHPUnit\Framework\Constraint\TraversableContainsEqual;

class EquipoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $equipo = Equipo::all();
        return view('equipo.index', compact('equipo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('equipo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required',
            'codigo' => 'required',
            'puntuacion' => 'required',
        ]);

        $equipo = new Equipo();

        $equipo->nombre = $request->nombre;
        $equipo->codigo = $request->codigo;
        $equipo->puntuacion = $request->puntuacion;

        $equipo->save();

        return redirect()->route('equipos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function show(Equipo $equipo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function edit(Equipo $equipo)
    {
        return view('equipo.edit', compact('equipo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Equipo $equipo)
    {
        $request->validate([
            'nombre' => 'required',
            'codigo' => 'required',
            'puntuacion' => 'required',
        ]);

        $equipo->nombre = $request->nombre;
        $equipo->codigo = $request->codigo;
        $equipo->puntuacion = $request->puntuacion;

        $equipo->save();

        return redirect()->route('equipos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Equipo  $equipo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Equipo $equipo)
    {
        $equipo->delete();

        return redirect()->route('equipos.index');
    }
}

resources/views/equipo/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>CREAR EQUIPO</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('equipos.store')}}" method="POST">
            @method('post')
            @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre Equipo</label>
                        <input type="text" class="form-control" id="nombre" name="nombre">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Codigo</label>
                        <input type="text" class="form-control" id="codigo" name="codigo">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Puntuación</label>
                        <input type="text" class="form-control" id="puntuacion" name="puntuacion">
                    </div>
                </div>
                <a href="{{route('equipos.index')}}" class="btn btn-primary ">Regresar</a>
                <button type="submit" class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/equipo/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>EDITAR EQUPO</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{route('equipos.update', $equipo)}}" method="POST">
            @method('put')
            @csrf
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nombre Equipo</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" value="{{$equipo->nombre}}">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Codigo</label>
                        <input type="text" class="form-control" id="codigo" name="codigo" value="{{$equipo->codigo}}">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Puntuación</label>
                        <input type="text" class="form-control" id="puntuacion" name="puntuacion" value="{{$equipo->puntuacion}}">
                    </div>
                </div>
                <a href="{{route('equipos.index')}}" class="btn btn-primary ">Regresar</a>
                <button type="submit" class="btn btn-success float-right">Crear</button>
            </form>
        </div>
    </div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/equipo/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')

<a class="btn btn-success mb-2" href="{{route('equipos.create')}}" role="button">Crear nuevo equipo</a>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table" id="tequipos" >
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nombre Equipo</th>
                    <th>Codigo</th>
                    <th>Puntuación</th>
                    <th>acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach($equipo as $equipo)
                    <tr>
                        <th>{{$equipo->id}}</th>
                        <td>{{$equipo->nombre}}</td>
                        <td>{{$equipo->codigo}}</td>
                        <td>{{$equipo->puntuacion}}</td>
                        <td width="100px">
                            <a class="btn btn-warning" href="{{route('equipos.edit',$equipo->id)}}" role="button"><i class="fas fa-edit"></i></a>
                            <form action="{{route('equipos.destroy', $equipo)}}" method="post"  style="display: inline">
                                @method('delete')
                                @csrf
                                <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                            </form>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@stop
@section('css')
@stop
@section('js')
    <script> console.log('Hi!'); </script>
    <script>
        $(document).ready(function () {
            $('#tequipos').DataTable({
                responsive: true,
                autoWidth: false,
                "language": {
                    "url": "{{asset("idioma/es_dtable.json")}}"
                }
            });
        });
    </script>
@stop